### PR TITLE
Renamed modules and switched to sample React app for front end

### PR DESCRIPTION
**Pull request by RichardInnocent**
Really sorry - this will probably break your project as I've renamed the base directories - may need a reimport or something.

And no I don't know what any of this code is... but it's React and it works soo....

### CODE REVIEW

**Comment by adlkucewicz** [comment]
Nice spot - this looks like it will make our lives much easier! Let me read up on it, though I did see that neutrino and nwb work better with a django backend. Maybe we can get away without using django...

**Comment by RichardInnocent** [comment]
> Nice spot - this looks like it will make our lives much easier! Let me read up on it, though I did see that neutrino and nwb work better with a django backend. Maybe we can get away without using django...

Let's discuss this in more detail. There are probably a myriad of different solutions, but there are two as I see it:

## Option 1 - Single binary
The single binary approach is where we could create a single binary to handle everything. This is probably what you've been learning how to do in your Django tutorials. Django (probably) solves this problem using an MVC pattern, so that:

- You have a controller that listens for HTTP requests on certain paths
- When a request is detected, we retrieve the appropriate response view for this (using React I imagine this is a stock HTTP page and CSS with some Javascript that actually does the rendering).
- Before the response is sent back, we inject the appropriate model into the view. The model will likely be retrieved from a database. This could take the form of replacing HTTP elements with user attributes or inserting them into the Javascript (although I'm very fuzzy on the latter bit - you probably have a better understanding).

This option has a few benefits - namely, it's fairly simple. We can pretty much create the whole thing in Django, and we can use elements of React as you've covered in the course.

## Option 2 - Front End vs. Back End binaries
In this, we separate the responsibilities between two binaries.

### Binary 1 - Front End
Responsible for rendering the front-end. This could be purely React based. Whenever we need to get information, rather than working out what this should be ourselves, we try and retrieve the information either before we return the view, or we retrieve it from the client-side.

The client-side rendering is what my organisation does, as it allows components to be rendered as soon as they're ready. I think the flow for that would be to return some Javascript that triggers off a request to the API to fetch the data it needs. As soon as the data for a particular component is returned, we load that component.

For example, on [YouTube](https://youtube.com), you'll likely notice that the page loads pretty instantly, but that the suggested videos are greyed out. As soon as the API responds with what videos to show, the video thumbnails are rendered on the page.

### Binary 2 - API
Responsible for returning all of the information that the front-end needs. Of course you can just use the API without requiring a front-end too which is pretty cool, as it allows for more flexibility in the future (e.g. mobile apps, chat bots etc, not that we'll do any of that likely). We _could_ add API functionality in Option 1, but this gets confusing with a separation of concerns and we're likely to end up duplicating some of the functionality. For example, if we have a page that returns information on the user _and_ expose this information via an API, what do we do? When we load the page, we'd either pretty much copy and paste the code we have for the API, or we'd make a call out to our own server to retrieve the same information which is unnecessary latency and complexity.

## Impact on Technology Choice
If we go with Option 1, the technology choices that serve the front-end and business logic are tightly coupled. For example, if we choose Django for the back end, we have to choose a front end technology that plays well with that, e.g. what you've been learning in your Django/React.js course.

Option 2 is more flexible. It really doesn't matter what we do either with, as long as they're vaguely appropriate for the task at hand.  For example, we could have a React.js front-end and a Django-based API. That said, if we're not getting along with Django so well, we could migrate to a Spring-based application (Java) and, as long as we preserve the API routes in the new version, the front end server wouldn't have to change at all.

## Conclusions
Ultimately, it's your decision. I think I have a _slight_ preference for splitting the front end and API as it means we can focus on the difficult business logic side of things without having to worry about the front end until we're ready and the amount we have to learn upfront is less overwhelming?

**Comment by RichardInnocent** [comment]
@adlkucewicz To add to the above, it looks like separating it out is somewhat standard as a practice.

From a [Wikipedia article on layered architectures](https://en.wikipedia.org/wiki/Multitier_architecture#Three-tier_architecture):

> In the web development field, three-tier is often used to refer to websites, commonly electronic commerce websites, which are built using three tiers:
\- A front-end web server serving static content, and potentially some cached dynamic content. In web-based application, front end is the content rendered by the browser. The content may be static or generated dynamically.
\- A middle dynamic content processing and generation level application server (e.g., Symfony, Spring, ASP.NET, Django, Rails, Node.js).
\- A back-end database or data store, comprising both data sets and the database management system software that manages and provides access to the data.

**Comment by adlkucewicz** [comment]
Nice research and summary.

I'm happy to continue with a layered approach, where we have our front and back end binaries. I agree that with this approach we can focus on the logic underpinning our application and then afterwards work on the React front end.

In regards, to the back end, I don't mind trying something other than Django as an opportunity to learn. Java would be completely new to me... In your opinion as you use Java daily, would it be the better option over Javascript for the back end?
I nabbed this from [Towardsdatascience](https://towardsdatascience.com/java-vs-javascript-which-is-the-best-choice-for-2019-a41ee2d3f78d#:~:text=By%20comparison%2C%20JavaScript%20is%20primarily,web%20app%20pages%20more%20interactive.&text=In%20short%2C%20when%20it%20comes,and%20interactivity%20is%20reserved%20for.). Which seems to imply Javascript would be good in our scenario...
image

**Comment by RichardInnocent** [comment]
I think I'd actually like to avoid Java if possible. I think this would be a good opportunity for me to learn other languages as I do get pretty bored of using the same one day in, day out 😂

That said I'm a little confused by the table. Java is a back-end technology and Javascript is front-end so I'm not really sure how they can be compared like this. I'd understand if it was Java vs. Node.js but it literally mentions Node.js on the Javascript side as though it's something completely different.

I think our main choices for the API are:
- Python (Django)
- Node.js
- C# (.NET)

I'll let you choose as I have no idea 😂

**Comment by adlkucewicz** [comment]
We just keep passing on the responsibility of the decision to the other person haha.

I used to know C#, but it has been years since I've used it and although I remember it being fairly easy to pick up. I'm inclined to go for Python or Node.js. 

So it's a question of either continuing with our current backend implementation with Django. Or ripping that out and going with Node.JS, which as it's based on JS, I think I will have a vague idea how to use it.

Or we just continue with Django now and do a second project after this that uses Node.JS?

**Comment by RichardInnocent** [comment]
> We just keep passing on the responsibility of the decision to the other person haha.
> 
> I used to know C#, but it has been years since I've used it and although I remember it being fairly easy to pick up. I'm inclined to go for Python or Node.js.
> 
> So it's a question of either continuing with our current backend implementation with Django. Or ripping that out and going with Node.JS, which as it's based on JS, I think I will have a vague idea how to use it.
> 
> Or we just continue with Django now and do a second project after this that uses Node.JS?

As you just suggested continuing with Django, let's go with that for now. I'll merge this PR so we can move forward.

**Pull request merged**
